---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: localhost:5000/echo_server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31808


#kubectl run -it --rm --restart=Never echo-server-cmd --image-pull-policy=Never --image=localhost/echo_server:latest --annotations="module.wasm.image/variant=compat" --overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"hostNetwork": true}}' /echo_server.wasm
