# from https://waylonwalker.com/til/install-rust/
---
- hosts: master
  gather_facts: yes
  become: no
  tasks:
    - name: Check if cargo is installed
      shell: command -v {{ ansible_env.HOME }}/.cargo/bin/cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y

    - name: Install wasm32-wasi toolchain
      when: cargo_exists is failed
      shell: "{{ ansible_env.HOME }}/.cargo/bin/rustup target add wasm32-wasi"
