---
- hosts: master
  become: no
  tasks:
    - name: Upload echo server project
      become: yes
      copy:
        remote_src: no
        src: ../echo_server
        dest: /opt
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Build project
      shell: "{{ ansible_env.HOME }}/.cargo/bin/cargo build --release --target wasm32-wasi"
      args:
        chdir: /opt/echo_server
