---
- hosts: master
  become: yes
  tasks:
    - name: Install packages to build crun
      apt:
        name:
          - make
          - git
          - gcc
          - build-essential
          - pkgconf
          - libtool
          - libsystemd-dev
          - libprotobuf-c-dev
          - libcap-dev
          - libseccomp-dev
          - libyajl-dev
          - go-md2man
          - libtool
          - autoconf
          - python3
          - automake
        state: present
        update_cache: yes

    - name: Clone crun repository
      git:
        repo: https://github.com/containers/crun
        dest: /opt/crun
        version: 1a62e947dc91555a15c631547c4d5cb7c1188c4b

    - name: Generate build configuration
      shell: ./autogen.sh && ./configure --with-wasmedge
      args:
        chdir: /opt/crun
        creates: Makefile

    - name: Build crun
      make:
        chdir: /opt/crun

    - name: Install crun
      make:
        target: install
        chdir: /opt/crun
